### ISSUE TITLE
作者我想问一下开头那个git clone文件怎么没有啊

### ISSUE THREAD

**Issue by TriumphHu** [pengzhangzhi/protein-sequence-diffusion-model#1]
https://github.com/pengzhangzhi/denoising-diffusion-protein-sequence 就是这个找不到

**Comment by pengzhangzhi** [comment]
不好意思，我改了下repo 名字。
`git clone https://github.com/pengzhangzhi/protein-sequence-diffusion-model `这个是正确的。

**Comment by TriumphHu** [comment]
作者你好，我是一个大四学生，最近毕设在做这方面的东西，我看您对扩散模型比较了解，我可以问你一点问题吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pengzhangzhi/protein-sequence-diffusion-model"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月18日(星期六) 中午1:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pengzhangzhi/protein-sequence-diffusion-model] 作者我想问一下开头那个git clone文件怎么没有啊 (Issue #1)





 
不好意思，我改了下repo 名字。
 git clone https://github.com/pengzhangzhi/protein-sequence-diffusion-model 这个是正确的。

**Comment by pengzhangzhi** [comment]
可以在这里问或者给我发邮件：）

**Comment by TriumphHu** [comment]
想问一下你这个代码是不是多卡运行的，我在本地单卡运行的时候出现了一点bug，不知道该怎么修改才能让我运行起来，我应该怎么修改呢

**Comment by pengzhangzhi** [comment]
可以把bug发出来

**Comment by TriumphHu** [comment]
model = SeqDiffusion.load_from_checkpoint(
    ckpt_path,
    'cuda:1'
)

这是源代码，如果这样运行，就会报错。RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1. 大概就是您是在服务器上用的1号显卡，但是我只有一块显卡，所以报错了，然后我尝试网上的方法，将代码改成了这样
model = SeqDiffusion.load_from_checkpoint(
    ckpt_path,
    map_location='cuda:0'
)


他又会报错说RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.大概就是说这块显卡已经在占用了，可是就是在电脑上运行的，这个该怎么解决呀



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pengzhangzhi/protein-sequence-diffusion-model"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月18日(星期六) 晚上6:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pengzhangzhi/protein-sequence-diffusion-model] 作者我想问一下开头那个git clone文件怎么没有啊 (Issue #1)





 
可以把bug发出来

**Comment by pengzhangzhi** [comment]
貌似我设置了GPU id  = 1， 你可以把它改成0

**Comment by TriumphHu** [comment]
太感谢了作者大大，我昨天找了一晚上，今天早上两分钟就解决了，超感谢你！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pengzhangzhi/protein-sequence-diffusion-model"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月19日(星期天) 上午10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pengzhangzhi/protein-sequence-diffusion-model] 作者我想问一下开头那个git clone文件怎么没有啊 (Issue #1)





 
貌似我设置了GPU id  = 1， 你可以把它改成0

**Comment by TriumphHu** [comment]
作者大大我这几天看了一下您的代码，想问一下如果我想在您的代码基础上，实现扩散模型生成smiles分子，您觉得能否可行呢，如果可行的话，需要修改哪些文件呢,还有就是您引用的这个esm 语言模型，是起到一个什么样的作用，辅助蛋白质序列生成？
如果您能百忙之中回复一下，我将不胜感激！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pengzhangzhi/protein-sequence-diffusion-model"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月19日(星期天) 上午10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pengzhangzhi/protein-sequence-diffusion-model] 作者我想问一下开头那个git clone文件怎么没有啊 (Issue #1)





 
貌似我设置了GPU id  = 1， 你可以把它改成0

**Comment by pengzhangzhi** [comment]
1. esm 辅助蛋白质序列生成. 
2. smiles分子生成可以参考其他工作，我没有做过
